version: '3.6'
services:
    trinity_world:
        build: ./world
        restart: always
        volumes:
        - trinity_world:/world
        - ./data:/data
        ports:
        - '1118:1118'
        - '8085:8085'

volumes:
    trinity_world:
